Repository yunionio/sdnagent, pull requests merged in 2019-04, with the labels that each got.

#1 Add OWNERS
  OWNERS
Labels: lgtm, size/S

#4 Automated cherry pick of #3: hostconfig: rework tests
  pkg/agent/utils/hostconfig.go
  pkg/agent/utils/hostconfig_test.go
Labels: size/M

#5 Automated cherry pick of #3: hostconfig: rework tests
  pkg/agent/utils/hostconfig.go
  pkg/agent/utils/hostconfig_test.go
Labels: size/M

#6 Automated cherry pick of #3: hostconfig: rework tests
  pkg/agent/utils/hostconfig.go
  pkg/agent/utils/hostconfig_test.go
Labels: size/M

#10 hostconfig: add MetadataPort()
  pkg/agent/utils/flowsource.go
  pkg/agent/utils/hostconfig.go
Labels: approved, lgtm, size/XS

#17 fix: remove ovs kmod dependency so as to deploy on centos 6
  build/sdnagent/vars
Labels: approved, lgtm, size/XS

#21 flowsource: 允许AiO机器访问自己的metadata服务
  pkg/agent/utils/flowsource.go
Labels: approved, lgtm, size/XS
