Repository yunionio/sdnagent, pull requests merged in 2020-09, with the labels that each got.

#110 docker buildx for sdnagent
  Makefile
  build/docker/Dockerfile
  scripts/cherry_pick_pull.sh
  scripts/docker_push.sh
Labels: approved, lgtm, size/L

#111 Automated cherry pick of #110: docker buildx for sdnagent
  Makefile
  build/docker/Dockerfile
  scripts/cherry_pick_pull.sh
  scripts/docker_push.sh
Labels: approved, lgtm, size/L

#109 Automated cherry pick of #107: build: eipgw: vrrp track script as monitor
  build/sdnagent/root/usr/share/sdnagent/ansible/files/keepalived-eipgw-notify.sh
  build/sdnagent/root/usr/share/sdnagent/ansible/templates/keepalived-eipgw.conf.j2
Labels: approved, lgtm, size/M

#107 build: eipgw: vrrp track script as monitor
  build/sdnagent/root/usr/share/sdnagent/ansible/files/keepalived-eipgw-notify.sh
  build/sdnagent/root/usr/share/sdnagent/ansible/templates/keepalived-eipgw.conf.j2
Labels: approved, lgtm, size/M

#108 Automated cherry pick of #107: build: eipgw: vrrp track script as monitor
  build/sdnagent/root/usr/share/sdnagent/ansible/files/keepalived-eipgw-notify.sh
  build/sdnagent/root/usr/share/sdnagent/ansible/templates/keepalived-eipgw.conf.j2
Labels: approved, lgtm, size/M

#115 sdnagent: be cooperative
  cmd/sdnagent/sdnagent.go
Labels: lgtm, size/XS

#116 Automated cherry pick of #115: sdnagent: be cooperative
  cmd/sdnagent/sdnagent.go
Labels: size/XS

#117 Automated cherry pick of #115: sdnagent: be cooperative
  cmd/sdnagent/sdnagent.go
Labels: size/XS

#119 Automated cherry pick of #115: sdnagent: be cooperative
  cmd/sdnagent/sdnagent.go
Labels: size/XS

#120 Automated cherry pick of #115: sdnagent: be cooperative
  cmd/sdnagent/sdnagent.go
Labels: size/XS

#112 vendor: bump yunion.io/x/onecloud to current tip of release/3.3
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cachedimage.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cachedimages_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/input.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/network.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/domain.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/project.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/taskman/subtasks.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/notifyclient/notify.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/cachedimages.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/cloudproviders.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/dbinstances.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/disks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/elasticcache_instances.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guest_actions.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guestnetworks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guests.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/hosts.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/initdb.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/loadbalancernetworks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/loadbalancers.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/networks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/purge.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/scaling_trigger.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/scheduled_tasks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/skus.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/storagecachedimages.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/storagecaches.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/vpcs.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/wires.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_cachedimages.go
  vendor/yunion.io/x/onecloud/pkg/vpcagent/models/modelset.go
Labels: approved, lgtm, size/XL

#113 Automated cherry pick of #112: vendor: bump yunion.io/x/onecloud to current tip of release/2.3
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cachedimage.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cachedimages_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/input.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/network.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/domain.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/project.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/taskman/subtasks.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/notifyclient/notify.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/cachedimages.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/cloudproviders.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/dbinstances.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/disks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/elasticcache_instances.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guest_actions.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guestnetworks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guests.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/hosts.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/initdb.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/loadbalancernetworks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/loadbalancers.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/networks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/purge.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/scaling_trigger.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/scheduled_tasks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/skus.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/storagecachedimages.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/storagecaches.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/vpcs.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/wires.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_cachedimages.go
  vendor/yunion.io/x/onecloud/pkg/vpcagent/models/modelset.go
Labels: approved, lgtm, size/XL

#114 Automated cherry pick of #112: vendor: bump yunion.io/x/onecloud to current tip of release/2.3
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cachedimage.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cachedimages_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/input.go
  vendor/yunion.io/x/onecloud/pkg/apis/compute/network.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/domain.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/project.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/db/taskman/subtasks.go
  vendor/yunion.io/x/onecloud/pkg/cloudcommon/notifyclient/notify.go
  vendor/yunion.io/x/onecloud/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/cachedimages.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/cloudproviders.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/dbinstances.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/disks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/elasticcache_instances.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guest_actions.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guestnetworks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/guests.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/hosts.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/initdb.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/loadbalancernetworks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/loadbalancers.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/networks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/purge.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/scaling_trigger.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/scheduled_tasks.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/skus.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/storagecachedimages.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/storagecaches.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/vpcs.go
  vendor/yunion.io/x/onecloud/pkg/compute/models/wires.go
  vendor/yunion.io/x/onecloud/pkg/mcclient/modules/mod_cachedimages.go
  vendor/yunion.io/x/onecloud/pkg/vpcagent/models/modelset.go
Labels: approved, lgtm, size/XL

#123 Automated cherry pick of #122: pull image for buildx
  scripts/docker_push.sh
Labels: approved, lgtm, size/XS

#122 pull image for buildx
  scripts/docker_push.sh
Labels: approved, lgtm, size/XS
